import logo from './logo.svg';
import './App.css';
import { dataschema } from "../src/draft7.json";
import {
  materialRenderers,
  materialCells,
} from '@jsonforms/material-renderers';
import { Generate } from '@jsonforms/core';
import React, { useState } from 'react';
import { JsonForms } from '@jsonforms/react';
import { Button } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.css';


var data = {}


function App() {
  const [data, setData] = useState({});
  return (
    <div className="App container">
      <br></br><br></br>
      <JsonForms
        schema={dataschema}
        data={data}
        renderers={materialRenderers}
        cells={materialCells}
        onChange={({ errors, data }) => setData(data)}
      />
      <Button onClick={() => setData(
        {
  "name": "weimarnetz",
  "api": "0.4.16",
  "url": "https://weimarnetz.de",
  "timeline": [
    {
      "timestamp": "2001-07-08T00",
      "description": "Initialzündung"
    },
    {
      "timestamp": "2005-05-31T00",
      "description": "Gründung Weimarnetz e.V."
    },
    {
      "timestamp": "2011-11-15T00",
      "description": "Weimarnetz e.V. anerkannt gemeinnützig"
    },
    {
      "timestamp": "2015-06-01",
      "description": "Freifunk in Camburg"
    },
    {
      "timestamp": "2020-03-15",
      "description": "Freifunk in Saalfeld"
    },
    {
      "timestamp": "2012-01-01",
      "description": "Freifunk in Süßenborn"
    }
  ],
  "support": {
    "club": {
      "city": "Weimar",
      "name": "Weimarnetz e.V.",
      "zip": "99423",
      "url": "https://weimarnetz.de",
      "street": "Marienstr. 18",
      "board": [
        "Rene Hoffmann",
        "Katrin Linke",
        "Andreas Bräu"
      ],
      "email": "vorstand@weimarnetz.de"
    },
    "donations": {
      "bankaccount": {
        "IBAN": "DE48 8306 5408 0004 1759 05",
        "BIC": "GENODEF1SLR"
      },
      "campaigns": [
        {
          "projectid": "14895",
          "provider": "betterplace"
        }
      ]
    }
  },
  "state": {
    "nodes": 94,
    "lastchange": "2021-07-01T08:00:01.392709",
    "focus": [
      "infrastructure/backbone",
      "Public Free Wifi",
      "Social Community Building",
      "Local services and content",
      "Free internet access"
    ]
  },
  "contact": {
    "matrix": "https://matrix.to/#/!SWQlgopOguLKBpcADp:bau-ha.us?via=bau-ha.us",
    "ml": "wireless-discuss@subsignal.org",
    "twitter": "@weimarnetz",
    "phone": "+493643544304",
    "facebook": "https://www.facebook.com/weimarnetz",
    "email": "kontakt@weimarnetz.de"
  },
  "location": {
    "city": "Weimar",
    "country": "DE",
    "lon": 11.338675,
    "additionalLocations": [
      {
        "lat": 51.05061455701514,
        "city": "Camburg",
        "lon": 11.709827184677122,
        "country": "DE"
      },
      {
        "lat": 50.64026225088228,
        "city": "Saalfeld",
        "lon": 11.380033493041992,
        "country": "DE"
      }
    ],
    "address": {
      "Street": "Marienstr.18",
      "Name": "Maschinenraum",
      "Zipcode": "99423"
    },
    "lat": 50.98953
  },
  "techDetails": {
    "updatemode": [
      "none",
      "manual"
    ],
    "firmware": {
      "url": "https://weimarnetz.de/category/router",
      "docs": "https://github.com/weimarnetz/packages",
      "name": "Brauhaus",
      "vpnaccess": "fwimage"
    },
    "legals": [
      "vpnnational",
      "institutions"
    ],
    "networks": {
      "ipv4": [
        {
          "network": "10.63.0.0/16"
        },
        {
          "network": "10.64.0.0/16"
        }
      ],
      "ipv6": [
        {
          "network": " 2001:bf7:1930::/44"
        }
      ]
    },
    "routing": [
      "OLSR"
    ]
  },
  "services": [
    {
      "internalUri": "http://77.87.48.29:8000",
      "serviceName": "Weimarnetz Radio powered by Bernd",
      "serviceDescription": "auto generated by olsr nameservice plugin"
    }
  ],
  "nodeMaps": [
    {
      "url": "https://weimarnetz.de/freifunk/topology.dot",
      "interval": "15m",
      "technicalType": "olsr-dot",
      "mapType": "structural"
    },
    {
      "url": "https://mapapi.weimarnetz.de",
      "interval": "5m",
      "technicalType": "openwifimap",
      "mapType": "geographical"
    },
    {
      "url": "https://hopglass.weimarnetz.de/",
      "interval": "5m",
      "technicalType": "hopglass",
      "mapType": "geographical"
    }
  ],
  "feeds": [
    {
      "category": "ics",
      "url": "https://ics.freifunk.net/tags/weimar.ics",
      "type": "ics",
      "name": "weimarnetz event calendar"
    },
    {
      "category": "blog",
      "url": "https://weimarnetz.de/rss.xml",
      "type": "rss",
      "name": "weimarnetz blog"
    }
  ],
  "socialprojects": {
    "website": "http://wireless.subsignal.org/index.php?title=Weimarnetz_hilft",
    "contact": "kontakt@weimarnetz.de",
    "number": 3
  }
}
        )} color='primary'>
        Initial Data
      </Button>
      <Button onClick={() => setData({})} color='primary'>
        Clear form data
      </Button>
    </div>
  );
}

export default App;
